image: node:9.11.1

pages:
 cache:
   paths:
   - node_modules/

 script:
 - npm i pnpm -g
 - pnpm install # npm install
 - pnpm docs:build # npm run docs:build
 artifacts:
   paths:
   - public
 only:
 - master